### ISSUE TITLE
zrlog-docker install crash 

### ISSUE THREAD

**Issue by 457452950** [94fzb/zrlog#160]
browser network package : {
    "message": "[Error-UNKNOWN] - 未知错误，请联系作者",
    "error": 9000
}

docker logs:
2023-07-19 21:01:50 [ERROR] 2023-07-19 13:01:50,383 com.zrlog.business.service.InstallService startInstall - install error 
2023-07-19 21:01:50 java.lang.NullPointerException
2023-07-19 21:01:50     at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
2023-07-19 21:01:50     at java.base/java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1089)
2023-07-19 21:01:50     at java.base/java.util.Properties.putAll(Properties.java:1311)
2023-07-19 21:01:50     at com.zrlog.business.service.InstallService.startInstall(InstallService.java:150)
2023-07-19 21:01:50     at com.zrlog.business.service.InstallService.install(InstallService.java:120)
2023-07-19 21:01:50     at com.zrlog.blog.web.controller.api.ApiInstallController.startInstall(ApiInstallController.java:68)
2023-07-19 21:01:50     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-07-19 21:01:50     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-07-19 21:01:50     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-07-19 21:01:50     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-07-19 21:01:50     at com.jfinal.aop.Invocation.invoke(Invocation.java:97)
2023-07-19 21:01:50     at com.zrlog.blog.web.interceptor.VisitorInterceptor.intercept(VisitorInterceptor.java:47)
2023-07-19 21:01:50     at com.zrlog.web.inteceptor.RouterInterceptor.intercept(RouterInterceptor.java:30)
2023-07-19 21:01:50     at com.jfinal.aop.Invocation.invoke(Invocation.java:91)
2023-07-19 21:01:50     at com.zrlog.blog.web.interceptor.MyI18nInterceptor.intercept(MyI18nInterceptor.java:22)
2023-07-19 21:01:50     at com.jfinal.aop.Invocation.invoke(Invocation.java:91)
2023-07-19 21:01:50     at com.zrlog.blog.web.interceptor.InitDataInterceptor.doIntercept(InitDataInterceptor.java:34)
2023-07-19 21:01:50     at com.zrlog.blog.web.interceptor.InitDataInterceptor.intercept(InitDataInterceptor.java:39)
2023-07-19 21:01:50     at com.jfinal.aop.Invocation.invoke(Invocation.java:91)
2023-07-19 21:01:50     at com.jfinal.core.ActionHandler.handle(ActionHandler.java:96)
2023-07-19 21:01:50     at com.zrlog.blog.web.handler.PluginHandler.handle(PluginHandler.java:38)
2023-07-19 21:01:50     at com.zrlog.blog.web.handler.BlogArticleHandler.handle(BlogArticleHandler.java:42)
2023-07-19 21:01:50     at com.zrlog.blog.web.handler.GlobalResourceHandler.handle(GlobalResourceHandler.java:61)
2023-07-19 21:01:50     at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:90)
2023-07-19 21:01:50     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2023-07-19 21:01:50     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2023-07-19 21:01:50     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
2023-07-19 21:01:50     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2023-07-19 21:01:50     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
2023-07-19 21:01:50     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
2023-07-19 21:01:50     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2023-07-19 21:01:50     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2023-07-19 21:01:50     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
2023-07-19 21:01:50     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
2023-07-19 21:01:50     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2023-07-19 21:01:50     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
2023-07-19 21:01:50     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
2023-07-19 21:01:50     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2023-07-19 21:01:50     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2023-07-19 21:01:50     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2023-07-19 21:01:50     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2023-07-19 21:01:50     at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 94fzb** [comment]
@457452950 需要按照流程来 https://github.com/94fzb/zrlog-docker，应该没有什么问题，如果无法解决请提供完整的操作信息，同时提供程序的版本
