### ISSUE TITLE
500：插件功能无法使用

### ISSUE THREAD

**Issue by anlingyi** [94fzb/zrlog#23]
zrlog版本：Version 1.10.0

服务器运行环境：
JDK1.8、Centos7、tomcat7/tomcat8、浏览器（IE/Google/Firefox）。
本地运行环境：
除系统（Win10）外，其他均与服务器环境配置相同。

本地环境完美运行，但服务器环境安装zrlog程序后，点击插件功能页面报500错误。

尝试过切换tomcat版本，删除plugin-core.jar，重新下载zrlog.war，再次部署，均没解决此问题。希望此问题能够得到解决，感谢作者！

页面错误：
500 Internal Server Error
SimpleWebServer/0.2

tomcat错误信息如下：
May 09, 2018 1:11:07 PM com.hibegin.http.server.handler.HttpDecodeRunnable$1 run
SEVERE: 
java.lang.NegativeArraySizeException
	at com.hibegin.common.util.BytesUtil.subBytes(BytesUtil.java:23)
	at com.hibegin.http.server.impl.HttpRequestDecoderImpl.doDecode(HttpRequestDecoderImpl.java:63)
	at com.hibegin.http.server.handler.HttpDecodeRunnable$1.run(HttpDecodeRunnable.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by 94fzb** [comment]
额, 看上去应该是 [simplewebserver](https://github.com/94fzb/simplewebserver) 的 bug. 不过 这个错看上去有点棘手 @anlingyi

**Comment by anlingyi** [comment]
本地运行是没问题的，就是部署到Linux时出现了这个问题

**Comment by 94fzb** [comment]
平是都是在 ubuntu 下面开发的,  服务器环境也是 ubuntu. , 都没有遇到这个情况. 所以说这个问题比较奇怪 @anlingyi

**Comment by 94fzb** [comment]
@anlingyi  构建了一个新的 plugin-core.jar 你可以试试。

**Comment by anlingyi** [comment]
问题已经解决了，非常感谢！ @94fzb

**Comment by 94fzb** [comment]
那应该 close 这个 issue
