### ISSUE TITLE
后台管理中的【文章管理】页面的搜索功能搜不到东西

### ISSUE THREAD

**Issue by Ennn** [94fzb/zrlog#29]
环境：
Chrome (69.0.3464.0)
ZrLog (2.0.0 - 4602099 (2018-06-27))
JDK (1.8.0_91-b14)
错误日志：
java.lang.NullPointerException
	at com.zrlog.service.ArticleService.wrapperSearchKeyword(ArticleService.java:156)
	at com.zrlog.service.ArticleService.page(ArticleService.java:130)
	at com.zrlog.web.controller.admin.api.ArticleController.index(ArticleController.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by 94fzb** [comment]
看上去应该是个 bug，应该特殊情况下面导致的（使用编辑器编辑的时候，检查没有生效，导致数据库保存content字段为 null了，触发了空指针） @Ennn

**Comment by 94fzb** [comment]
处理方式应该找到对应的文章编辑一下，然后就能正常的检索了 @Ennn
